services:
  - type: web
    name: mynews-api
    runtime: node
    plan: free
    rootDir: ./
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://my-news-three.vercel.app
      - key: FRONTEND_URL
        value: https://my-news-three.vercel.app
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
